spring:
  config:
    import: "optional:vault:///spring-boot-tutorial?prefix=app.vault.secrets."
  cloud:
    vault:
      uri: "${VAULT_URI:http://localhost:8200}"

server:
  error:
    include-stacktrace: "always"
