spring:
  application:
    name: "container"
  messages:
    basename: "i18n/messages"
  threads:
    virtual:
      enabled: true
  profiles:
    active:
      # - "development"
      - "production"

logging:
  config: "classpath:log/logback-spring.xml"

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: "when-authorized"
  endpoints:
    web:
      exposure:
        include: "health,metrics"
