networks:
  # xxx.
  reverse-proxy:
    external: true

services:
  app:
    # xxx.
    image: "lsampaioweb/app:1.0"

    # xxx.
    container_name: "app"

    # xxx.
    restart: "unless-stopped"

    # xxx.
    environment:
      - "SPRING_PROFILES_ACTIVE=development"
      # - "SPRING_PROFILES_ACTIVE=production"

    # xxx.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.rule=Host(`app.lan.homelab`)"
      - "traefik.http.routers.app.middlewares=headers-rate-limit@file,headers-default@file,headers-security@file"

    # xxx.
    networks:
      - "reverse-proxy"

    # xxx.
    volumes:
      # xxx.
      - "./logs:/home/app/logs"

    # xxx.
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost:8080/actuator/health/ping || exit 1"]
      start_period: "4s"
      interval: "10s"
      timeout: "2s"
      retries: 2
