# Because the API Rest application is running on 8080.
server:
  port: 8081

spring:
  application:
    name: "http-client"

  threads:
    virtual:
      enabled: true

  # Only necessary if you want to change some settings.
  http:
    client:
      connect-timeout: 5000
      read-timeout: 5000

logging:
  config: "classpath:log/logback-spring.xml"

external:
  api:
    base-url: "http://localhost:8080/api/v1"
    users: "${external.api.base-url}/users"
