networks:
  #
  reverse-proxy:
    external: true

services:
  app:
    #
    image: "lsampaioweb/app:1.0"
    #
    container_name: "app"

    #
    user: "1002:1002"

    #
    restart: "unless-stopped"

    #
    environment:
      - "SPRING_PROFILES_ACTIVE=development"
      # - "SPRING_PROFILES_ACTIVE=production"
      # - "SERVER_PORT=8081"

    #
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.rule=Host(`app.lan.homelab`)"
      - "traefik.http.routers.app.middlewares=headers-rate-limit@file,headers-default@file,headers-security@file"

    #
    networks:
      - "reverse-proxy"

    #
    volumes:
      # Adjust the date and time of the container.
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

      # Files and folders for the container.
      - "./logs:/home/app/logs"

    #
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- http://localhost:8080/actuator/health/ping || exit 1"]
      start_period: "4s"
      interval: "10s"
      timeout: "2s"
      retries: 2
