server:
  port: 9443
  error:
    include-stacktrace: "never"

management:
  endpoint:
    health:
      show-details: "never"

springdoc:
  swagger-ui:
    enabled: false

app:
  rabbitmq:
    exchange: "${RABBITMQ_EXCHANGE:orders.headers.exchange}"
    queue-one: "${RABBITMQ_QUEUE_ONE:orders.headers.queue.created}"
    queue-two: "${RABBITMQ_QUEUE_TWO:orders.headers.queue.audit}"
    header-name: "${RABBITMQ_HEADER_NAME:eventType}"
    header-value-one: "${RABBITMQ_HEADER_VALUE_ONE:order.created}"
    header-value-two: "${RABBITMQ_HEADER_VALUE_TWO:order.audit}"
