http:
  middlewares:
    headers-rate-limit:
      rateLimit:
        burst: 50
        average: 25
        # period: "1s"

    headers-inFlightReq:
      inFlightReq:
        amount: 25

    headers-default:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-For"
          - "X-Forwarded-Host"
          - "X-Forwarded-Port"
          - "X-Forwarded-Proto"
          - "X-Forwarded-Server"
          - "X-Real-Ip"

    headers-security:
      headers:
        frameDeny: true
        browserXssFilter: true
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        contentTypeNosniff: true
        accessControlMaxAge: 100
        addVaryheader: true
        referrerPolicy: "origin-when-cross-origin"
