# Part 1. Config here.
# user:
#   role: "Default"

# Part 2. Config in remote server.
spring:
  application:
    name: "cloud-config-client"
  threads:
    virtual:
      enabled: true
  messages:
    basename: "i18n/messages"
  profiles:
    active:
      # - "development"
      - "production"
  cloud:
    config:
      username: "${USERNAME}"
      password: "${PASSWORD}"
  config:
    # import: "configserver:http://localhost:8080"
    import: "optional:configserver:https://jump-server-01.lan.homelab:9443"

logging:
  config: "classpath:log/logback-spring.xml"

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: "when-authorized"

app:
  hello:
    role: "${user.role}"
    server-port: "${server.port}"
