spring:
  application:
    name: "cloud-config-client"
  profiles:
    # active: "default"
    active: "development"
    # active: "production"
  config:
    import: "configserver:http://localhost:8080"
  # cloud:
  #   config:
  #     uri: "http://localhost:8080"
      # name: "cloud-config-client"
      # profile: "development"
      # label: "main"
      # username: "admin"
      # password: "secret"

  # cloud:
  #   security:
  #     user:
  #       name: "root"
  #       password: "s3cr3t"

logging:
  config: "classpath:log/logback-spring.xml"
