# Part 1. Config here.
# user:
#   role: "Default"

# server:
#   port: 8081

# Part 2. Config in remote server.
spring:
  application:
    name: "cloud-config-client"
  profiles:
    # active: "default"
    active: "development"
    # active: "production"
  cloud:
    config:
      username: "${USERNAME}"
      password: "${PASSWORD}"
  config:
    # import: "configserver:http://localhost:8080"
    import: "configserver:https://jump-server-01.homelab:9443"

logging:
  config: "classpath:log/logback-spring.xml"
