spring:
  application:
    name: "cloud-config-server"
  cloud:
    config:
      server:
        git:
          # uri: "https://github.com/{application}"
          # One repository for all clients apps.
          uri: "file://${user.home}/git/datacenter/spring-boot/tutorial/samples/08-cloud-config/git-config"
          cloneOnStart: true
          search-paths: "{application}/{profile}"

          # One repository per client app.
          # repos:
          #   client-01:
          #     pattern: "cloud-config-client"
          #     search-paths: "{application}/{profile}"
          #     uri: "..."
          #   client-02:
          #     pattern: "client-02"
          #     search-paths: "{application}/{profile}"
          #     uri: "..."
  security:
    user:
      name: "${USERNAME}"
      password: "${PASSWORD}"

# Part 1 - Http
# server:
#   port: 8080

# Part 1 - Https
# My custom environment variables.
KEY_STORE_PASSWORD: "${KEY_STORE_PASSWORD_MY_HTTPS_APP}"

server:
  port: 9443
  ssl:
    enabled: true
    protocol: "TLS"
    enabled-protocols: "TLSv1.3"
    key-store-type: "PKCS12"
    key-store: "classpath:ssl/my-cert.p12"
    key-store-password: ${KEY_STORE_PASSWORD}
  http2:
    enabled: true


logging:
  config: "classpath:log/logback-spring.xml"
