# My custom environment variables.
# KEY_STORE_PASSWORD: "${KEY_STORE_PASSWORD_MY_HTTPS_APP}"

spring:
  application:
    name: "cloud-config-server"
  cloud:
    config:
      server:
        git:
          # uri: "https://example.com/my/repo"
          uri: "file://${user.home}/git/datacenter/spring-boot/tutorial/samples/08-cloud-config/git-config"
          clone-on-start: true
          searchPaths: "{application}/{profile}"
  # security:
  #   user:
  #     name: "root"
  #     password: "s3cr3t"

# management:
#   security:
#     enabled: false

server:
  # port: 9443
  port: 8080
  # ssl:
  #   enabled: true
  #   enabled-protocols: "TLSv1.3"
  #   key-store-type: "PKCS12"
  #   key-store: "classpath:ssl/my-cert.p12"
  #   key-store-password: ${KEY_STORE_PASSWORD}
  # http2:
  #   enabled: true

logging:
  config: "classpath:log/logback-spring.xml"
