server:
  port: 8080
  error:
    include-stacktrace: "always"

management:
  endpoint:
    health:
      show-details: "always"

springdoc:
  swagger-ui:
    enabled: true

app:
  rabbitmq:
    exchange: "dev.orders.topic.exchange"
    queue-one: "dev.orders.topic.queue.orders"
    queue-two: "dev.orders.topic.queue.audit"
    routing-key-one: "dev.order.*"
    routing-key-two: "dev.audit.#"
