server:
  port: 9443
  error:
    include-stacktrace: "never"

management:
  endpoint:
    health:
      show-details: "never"

springdoc:
  swagger-ui:
    enabled: false

app:
  rabbitmq:
    exchange: "${RABBITMQ_EXCHANGE:orders.topic.exchange}"
    queue-one: "${RABBITMQ_QUEUE_ONE:orders.topic.queue.orders}"
    queue-two: "${RABBITMQ_QUEUE_TWO:orders.topic.queue.audit}"
    routing-key-one: "${RABBITMQ_ROUTING_KEY_ONE:order.*}"
    routing-key-two: "${RABBITMQ_ROUTING_KEY_TWO:audit.#}"
