management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
  endpoint:
    health:
      show-details: "always"

server:
  error:
    include-stacktrace: "always"
  port: 8084

app:
  rabbitmq:
    exchange: "dev.orders.headers.exchange"
    queue-one: "dev.orders.headers.queue.created"
    queue-two: "dev.orders.headers.queue.audit"
    header-name: "eventType"
    header-value-one: "order.created"
    header-value-two: "order.audit"
