spring:
  application:
    name: "rabbitmq-headers"
  messages:
    basename: "i18n/messages"
  threads:
    virtual:
      enabled: true
  profiles:
    active:
      # - "development"
      - "production"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "admin"
    password: "${RABBITMQ_ROOT_PASSWORD}"

logging:
  config: "classpath:log/logback-spring.xml"

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
  endpoint:
    health:
      show-details: "when-authorized"

app:
  rabbitmq:
    exchange: "orders.headers.exchange"
    queue-one: "orders.headers.queue.created"
    queue-two: "orders.headers.queue.audit"
    header-name: "eventType"
    header-value-one: "order.created"
    header-value-two: "order.audit"
