server:
  port: 8080
  error:
    include-stacktrace: "always"

management:
  endpoint:
    health:
      show-details: "always"

springdoc:
  swagger-ui:
    enabled: true

app:
  rabbitmq:
    exchange: "dev.orders.headers.exchange"
    queue-one: "dev.orders.headers.queue.created"
    queue-two: "dev.orders.headers.queue.audit"
    header-name: "eventType"
    header-value-one: "order.created"
    header-value-two: "order.audit"
