spring:
  application:
    name: "rabbitmq-direct"
  messages:
    basename: "i18n/messages"
  threads:
    virtual:
      enabled: true
  profiles:
    active:
      # - "development"
      - "production"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "admin"
    password: "${RABBITMQ_ROOT_PASSWORD}"

logging:
  config: "classpath:log/logback-spring.xml"

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
  endpoint:
    health:
      show-details: "when-authorized"

app:
  rabbitmq:
    exchange: "orders.direct.exchange"
    queue: "orders.direct.queue"
    routing-key: "order.created"
