management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
  endpoint:
    health:
      show-details: "never"

server:
  error:
    include-stacktrace: "never"

app:
  rabbitmq:
    exchange: "${RABBITMQ_EXCHANGE:orders.direct.exchange}"
    queue: "${RABBITMQ_QUEUE:orders.direct.queue}"
    routing-key: "${RABBITMQ_ROUTING_KEY:order.created}"
