server:
  port: 8080
  error:
    include-stacktrace: "always"

management:
  endpoint:
    health:
      show-details: "always"

spring:
  sql:
    init:
      mode: "always"
      schema-locations: "classpath:sql/schema.sql"

springdoc:
  swagger-ui:
    enabled: true
