spring:
  application:
    name: "rabbitmq-topic"
  messages:
    basename: "i18n/messages"
  threads:
    virtual:
      enabled: true
  profiles:
    active:
      # - "development"
      - "production"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "admin"
    password: "${RABBITMQ_ROOT_PASSWORD}"

logging:
  config: "classpath:log/logback-spring.xml"

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
  endpoint:
    health:
      show-details: "when-authorized"

app:
  rabbitmq:
    exchange: "orders.topic.exchange"
    queue-one: "orders.topic.queue.orders"
    queue-two: "orders.topic.queue.audit"
    routing-key-one: "order.*"
    routing-key-two: "audit.#"
