server:
  port: 9443
  error:
    include-stacktrace: "never"

management:
  endpoint:
    health:
      show-details: "never"

springdoc:
  swagger-ui:
    enabled: false

app:
  rabbitmq:
    exchange: "${RABBITMQ_EXCHANGE:orders.fanout.exchange}"
    queue-one: "${RABBITMQ_QUEUE_ONE:orders.fanout.queue.one}"
    queue-two: "${RABBITMQ_QUEUE_TWO:orders.fanout.queue.two}"
