spring:
  application:
    name: "actuator"
  profiles:
    active:
      # - "development"
      - "production"

management:
  endpoints:
    web:
      exposure:
        # include: "*"
        include: "health,info,metrics"

  endpoint:
    health:
      probes:
        enabled: true
      show-details: "when-authorized"

logging:
  config: "classpath:log/logback-spring.xml"
  logback:
    rollingpolicy:
      max-file-size: "10MB"
      max-history: "7"
      total-size-cap: "1GB"
