version: "3.9"

networks:
  reverse-proxy:
    external: true

services:
  traefik:
    image: "traefik:latest"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: "start-first"
      restart_policy:
        condition: "on-failure"
    networks:
      - "reverse-proxy"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Traefik will listen to new containers.
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # Adjust the date and time of the container.
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      # Files and folders for the container.
      - "./apps/:/etc/traefik/apps/"
      - "./certificates/:/etc/traefik/certificates/"
      - "./config/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./log/:/var/log/traefik/"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      start_period: "5s"
      interval: "10s"
      timeout: "2s"
      retries: 2
