spring:
  application:
    name: "virtual-threads"
  messages:
    basename: "i18n/messages"
  threads:
    virtual:
      enabled: true
  profiles:
    active:
      # - "development"
      - "production"

# Tomcat threads defaults to 200, 0 is unlimited.
# server:
#   tomcat:
#     threads:
#       max: 10

logging:
  config: "classpath:log/logback-spring.xml"

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: "when-authorized"
