spring:
  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 8080
  error:
    include-stacktrace: "always"

management:
  endpoint:
    health:
      show-details: "always"

springdoc:
  swagger-ui:
    enabled: true
