spring:
  config:
    import: "optional:configserver:https://localhost:9443"

server:
  port: 8080
  error:
    include-stacktrace: "never"

management:
  endpoint:
    health:
      show-details: "never"

springdoc:
  swagger-ui:
    enabled: false
