spring:
  application:
    name: "websocket-client"

  profiles:
    active:
      # - "development"
      - "production"

  messages:
    basename: "i18n/messages"

  threads:
    virtual:
      enabled: true

server:
  port: 8091

logging:
  config: "classpath:log/logback-spring.xml"

app:
  websocket-client:
    server-ws-url: "http://localhost:8090/ws"
