spring:
  application:
    name: "restapi"
  messages:
    basename: "i18n/messages"
  threads:
    virtual:
      enabled: true
  autoconfigure:
    exclude: "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"
  profiles:
    active:
      # - "development"
      - "production"

logging:
  config: "classpath:log/logback-spring.xml"

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: "when-authorized"
