server:
  port: 9443
  error:
    include-stacktrace: "never"

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: "never"

springdoc:
  swagger-ui:
    enabled: false
