server:
  port: 8080
  error:
    include-stacktrace: "always"

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
  endpoint:
    health:
      show-details: "always"
