spring:
  application:
    name: "security"
  threads:
    virtual:
      enabled: true
  profiles:
    active:
      # - "development"
      - "production"
  messages:
    basename: "i18n/messages"
    encoding: "UTF-8"
    default-locale: "en"
    fallback-to-system-locale: false

app:
  security:
    credentials:
      user:
        username: ${SECURITY_USER_USERNAME}
        password: ${SECURITY_USER_PASSWORD}
      admin:
        username: ${SECURITY_ADMIN_USERNAME}
        password: ${SECURITY_ADMIN_PASSWORD}

logging:
  config: "classpath:log/logback-spring.xml"
  logback:
    rollingpolicy:
      max-file-size: "10MB"
      max-history: "7"
      total-size-cap: "1GB"

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
      show-details: "when-authorized"

server:
  error:
    include-stacktrace: "never"

springdoc:
  api-docs:
    enabled: false
    path: /api-docs
  swagger-ui:
    enabled: false
    path: /swagger-ui.html
