management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
  endpoint:
    health:
      show-details: "never"

server:
  error:
    include-stacktrace: "never"

app:
  rabbitmq:
    exchange: "${RABBITMQ_EXCHANGE:orders.headers.exchange}"
    queue-one: "${RABBITMQ_QUEUE_ONE:orders.headers.queue.created}"
    queue-two: "${RABBITMQ_QUEUE_TWO:orders.headers.queue.audit}"
    header-name: "${RABBITMQ_HEADER_NAME:eventType}"
    header-value-one: "${RABBITMQ_HEADER_VALUE_ONE:order.created}"
    header-value-two: "${RABBITMQ_HEADER_VALUE_TWO:order.audit}"
