spring:
  application:
    name: "websocket-server"

  profiles:
    active:
      # - "development"
      - "production"

  messages:
    basename: "i18n/messages"

  threads:
    virtual:
      enabled: true

server:
  port: 8090

logging:
  config: "classpath:log/logback-spring.xml"
