spring:
  application:
    name: "async-basics"
  messages:
    basename: "i18n/messages"
    encoding: "UTF-8"
    default-locale: "en"
    fallback-to-system-locale: false
  threads:
    virtual:
      enabled: true
  profiles:
    active:
      # - "development"
      - "production"

logging:
  config: "classpath:log/logback-spring.xml"
  logback:
    rollingpolicy:
      max-file-size: "10MB"
      max-history: "7"
      total-size-cap: "1GB"
    path: "logs"

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: "when-authorized"
      probes:
        enabled: true

app:
  security:
    username: "${ASYNC_USER_USERNAME:async-user}"
    password: "${ASYNC_USER_PASSWORD}"
