spring:
  application:
    name: "rabbitmq"

  profiles:
    active:
      - "development"
      # - "production"

  messages:
    basename: "i18n/messages"

  threads:
    virtual:
      enabled: true

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "admin"
    password: "${RABBITMQ_ROOT_PASSWORD}"

logging:
  config: "classpath:log/logback-spring.xml"
