# Because the API Rest application is running on 8080.
spring:
  application:
    name: "http-client"
  messages:
    basename: "i18n/messages"
    encoding: "UTF-8"
    default-locale: "en"
    fallback-to-system-locale: false
  autoconfigure:
    exclude: "org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration"
  profiles:
    active:
      # - "development"
      - "production"

logging:
  config: "classpath:log/logback-spring.xml"
  logback:
    rollingpolicy:
      max-file-size: "10MB"
      max-history: "7"
      total-size-cap: "1GB"

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: "when-authorized"

external:
  api:
    base-url: "http://localhost:8080/api/v1"
    users: "${external.api.base-url}/users"
    connect-timeout: "2s"
    read-timeout: "5s"
