spring:
  application:
    name: "thymeleaf"

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"

  endpoint:
    health:
      show-details: "always"

logging:
  config: "classpath:log/logback-spring.xml"
