server:
  port: 9443
  error:
    include-stacktrace: "never"

management:
  endpoint:
    health:
      show-details: "never"

springdoc:
  swagger-ui:
    enabled: false

app:
  rabbitmq:
    exchange: "${RABBITMQ_EXCHANGE:orders.direct.exchange}"
    queue: "${RABBITMQ_QUEUE:orders.direct.queue}"
    routing-key: "${RABBITMQ_ROUTING_KEY:order.created}"
