server:
  port: 8080
  error:
    include-stacktrace: "always"

management:
  endpoint:
    health:
      show-details: "always"

springdoc:
  swagger-ui:
    enabled: true

app:
  rabbitmq:
    exchange: "dev.orders.direct.exchange"
    queue: "dev.orders.direct.queue"
    routing-key: "dev.order.created"
