http:
  routers:
    secure-loadbalancer:
      entryPoints:
        - "websecure"
      tls:
        options: "tls-loadbalancer"
      rule: "Host(`loadbalancer.lan.homelab`)"
      middlewares:
        - "headers-rate-limit-loadbalancer"
        - "headers-inFlightReq"
        - "headers-default"
        - "headers-security"
      service: "api@internal"
