management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
  endpoint:
    health:
      show-details: "always"

server:
  error:
    include-stacktrace: "always"
  port: 8082

app:
  rabbitmq:
    exchange: "dev.orders.fanout.exchange"
    queue-one: "dev.orders.fanout.queue.one"
    queue-two: "dev.orders.fanout.queue.two"
